#!/usr/bin/env python3
import csv
import os
import re
import glob
import json
import argparse
import logging
import uuid

from xml.etree import cElementTree as ElementTree

#-----------------------
# Logger
#-----------------------
class LoggerFactory():
    def __init__(self):
        pass

    def getLogger(self, name):
        logger = logging.getLogger(name)
        ch = logging.StreamHandler()
        ch.setLevel(logging.INFO)
        formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        ch.setFormatter(formatter)
        logger.addHandler(ch)
        logger.setLevel(logging.DEBUG)

        return logger


LoggerFactory = LoggerFactory()

#-----------------------
# Thresholds
#-----------------------
class InstanceThresholdMigrator():
    def __init__(self, thresholds):
        self.thresholds = thresholds.set

        self.conditionMap = {
            ">": "GREATER_THAN",
            "<": "SMALLER_THAN",
            "=": "EQUALS",
            "<=": "SMALLER_OR_EQUALS",
            ">=": "GREATER_OR_EQUALS"
        }

        self.absoluteConditionMap = {
            ">": "ABOVE",
            "<": "BELOW"
        }

        self.baselineMap = {
            "Not Enabled": "notEnabled",
            "Auto": "auto",
            "Hourly Baseline": "hourly",
            "Daily Baseline": "daily",
            "Weekly Baseline": "weekly",
            "Hourly And Daily": "hourlyAndDaily",
            "Hourly And Daily Baseline": "hourlyAndDaily",
            "All Baselines": "all"
        }

        self.basetypeMap = {
            "Not Enabled": "notEnabled",
            "Auto": "auto",
            "Hourly": "hourly",
            "Daily": "daily",
            "Weekly": "weekly",
            "Hourly And Daily": "hourlyAndDaily",
            "All Baselines": "all"
        }

    def migrate(self):
        logger.info(f"Migrating {len(self.thresholds)} instance thresholds ...")

        configurations = []
        
        for threshold in self.thresholds:
            try:
                configurations.append({
                    "agent": threshold["agent"],
                    "port": threshold["port"],
                    "solution": None,
                    "monitorType": threshold["monitorType"],
                    "attribute": threshold["attribute"],
                    "configurationType": "serverThresholdConfiguration",
                    "details" : {
                        "absoluteDeviation" : threshold["absoluteDeviation"],
                        "autoClose": threshold["autoClose"],
                        "comparison": self.absoluteConditionMap[threshold["condition"]] if threshold["thresholdType"] == "absolute" else self.conditionMap[threshold["condition"]] ,
                        "durationInMins": threshold["duration"],
                        "minimumSamplingWindow": threshold["minSampleWindow"],
                        "outsideBaseline": self.baselineMap[threshold["outsideBasline"]],
                        "percentDeviation": threshold["deviation"],
                        "predict": threshold["predict"],
                        "severity": threshold["severity"],
                        "threshold": threshold["value"]
                    },
                    "instanceName": threshold["instance"],
                    "type": threshold["thresholdType"]
                })
            except Exception as error:
                logger.error("An unexpected exception occured while migrating instance threshold. Continuing processing but entry is ignored.")
                logger.error(f"agent: {threshold['agent']}, port: {threshold['port']}, monitorType: {threshold['monitorType']}, attribute: {threshold['attribute']}, instance: {threshold['instance']}, type: {threshold['thresholdType']}")
                logger.error(error)

        return configurations

class ThresholdSet():
    def __init__(self):
        selt.set = []
        
class FileThresholdSet(ThresholdSet):
    def __init__(self, filename):
        self.set = []
        self.filename = filename

    def load(self):
        logger.info(f"Loading Server Thresholds from '{self.filename}' ...")

        with open(self.filename) as input:
            reader = csv.reader(input)
            header = True 
            for row in reader:
                # skip header
                if (header and row[0] == "PATROL Agent" and row[1] == "Monitor Type"): continue
                header = False

                if row[19] == "false":
                    self.set.append({
                        "agent": row[0].split(':')[0],
                        "port": row[0].split(':')[1],
                        "monitorType": row[1],
                        "device": row[2],
                        "instance": row[3],
                        "attribute": row[4],
                        "severity": row[5].upper(),
                        "duration": row[6],
                        "condition": row[7],
                        "value": row[8],
                        "uom": row[9],
                        "outsideBasline": row[10],
                        "autoClose": row[11],
                        "predict": row[12],
                        "minSampleWindow": row[13] if row[13] != "" else None,
                        "baselineType": row[14],
                        "absoluteDeviation": row[15] if row[15] != "" else None,
                        "deviation": row[16],
                        "suppressEvents": row[17],
                        "thresholdType": row[18].lower()
                    })

#-----------------------
# Policies
#-----------------------
class PolicyFactory():
    def __init__(self, kmRepository, defaults = {}):
        self.configurations = []
        self.kmRepository = kmRepository
        self.defaults = defaults

    def generatePolicies(self):
        logger.info("Generating policies ...")
        policies = {}
        for configuration in self.configurations:
            # no agent policy for this agent has been created
            agent = f"{configuration['agent']}:{configuration['port']}"
            if not agent in policies:
                policies[agent] = self.createAgentPolicy(configuration["agent"], configuration["port"])

            # configuration is a server threshold configuration
            if configuration["configurationType"] == "serverThresholdConfiguration":
                configuration["solution"] = self.kmRepository.monitors[configuration["monitorType"]]["solution"]
                configuration["release"] = self.kmRepository.monitors[configuration["monitorType"]]["release"]

                self.generateServerThresholdConfiguration(policies[agent], configuration)

        logger.info(f"Generated {len(policies)} policies.")
        return policies

    def generateServerThresholdConfiguration(self, policy, configuration):
        agent = configuration["agent"]
        port = configuration["port"]
        if not "serverThresholdConfiguration" in policy:
            policy["serverThresholdConfiguration"] = {
                "solutionThresholds": []
            }

        # Generate solution
        found = False
        for solution in policy["serverThresholdConfiguration"]["solutionThresholds"]:
            if solution["solutionName"] == configuration["solution"] and solution["solutionVersion"] == configuration["release"]:
                found = True
                break

        if not found:
            solution = {
                "solutionName": configuration["solution"],
                "solutionVersion": configuration["release"],
                "monitors": [] 
            }

            policy["serverThresholdConfiguration"]["solutionThresholds"].append(solution)

        # Generate monitor
        found = False
        for monitor in solution["monitors"]:
            if monitor["monitorType"] == configuration["monitorType"]:
                found = True
                break

        if not found:
            monitor = {
                "monitorType": configuration["monitorType"],
                "attributes": []
            }

            solution["monitors"].append(monitor)

        # Generate attribute
        found = False
        for attribute in monitor["attributes"]:
            if attribute["attributeName"] == configuration["attribute"]:
                found = True
                break

        if not found:
            attribute = {
                "active": -1,
                "attributeName": configuration["attribute"],
                "regEx": False,
                "thresholds": []
            }

            monitor["attributes"].append(attribute)

        # Generate Threshold
        attribute["thresholds"].append({
            "details": configuration["details"],
            "instanceName": configuration["instanceName"],
            "matchDeviceName": False,
            "type": configuration["type"]
        })


    def createAgentPolicy(self, agent, port):
        name = f"{agent}-{port}-Thresholds"
        logger.debug(f"Generating agent policy '{name}' ...")
        return {
            "agentSelectionCriteria": f"agentName EQUALS \"{agent}\" AND agentPort NUMBER_EQUALS \"{port}\"",
            "associatedUserGroup": self.defaults["associatedUserGroup"] if "associatedUserGroup" in self.defaults else "Administrators",
            "description": self.defaults["description"] if "description" in self.defaults else "Auto Generated Agent Policy",
            "enabled": self.defaults["enabled"] if "enabled" in self.defaults else False,
            "id": str(uuid.uuid4()),
            "name": name,
            "owner": self.defaults["owner"] if "owner" in self.defaults else "admin",
            "precedence": self.defaults["agentPrecedence"] if "agentPrecedence" in self.defaults else "399",
            "shared": self.defaults["shared"] if "shared" in self.defaults else False,
            "tenant": {
                "id": self.defaults["tenantId"] if "tenantId" in self.defaults else "*",
                "name": self.defaults["tenantName"] if "tenantName" in self.defaults else "*"
            },
            "type": "monitoring"
        }


#-----------------------
# KMRepository
#-----------------------
class KMRepository():
    def __init__(self, dirname = None):
        self.dirname = dirname
        self.monitors = {}

    def load(self):
        logger.info(f"Loading TrueSight repository located in directory '{self.dirname}' ...")
        pattern = re.compile(f".*[{os.path.sep}]([^{os.path.sep}]*)[{os.path.sep}]([^{os.path.sep}]*)[{os.path.sep}]lib[{os.path.sep}]knowledge$")

        # walk through the bmc_products directory and find all the lib/knowledge/*.xml files
        for dirname, dirs, files in os.walk(self.dirname):
            match = pattern.match(dirname)
            if match:
                for file in files:
                    if file.endswith(".xml"):
                        root = ElementTree.parse(f"{dirname}{os.path.sep}{file}").getroot()

                        self.monitors[file[:-4]] = {
                            "monitorType": file[:-4],
                            "solution": match[1],
                            "description": root.attrib["description"] if "description" in root.attrib else None,
                            "majorVersion": root.attrib["majorVersion"] if "majorVersion" in root.attrib else None,
                            "minorVersion": root.attrib["minorVersion"] if "minorVersion" in root.attrib else None,
                            "package": root.attrib["package"] if "package" in root.attrib else None,
                            "productcode": root.attrib["productcode"] if "productcode" in root.attrib else None,
                            "release": root.attrib["release"] if "release" in root.attrib else match[2]
                        }

    def saveCache(self, path, filename):
        logger.info(f"Writing KM repsoitory to cache '{path}{os.path.sep}{filename}' ...")
        os.makedirs(path, exist_ok = True)
        with open(f"{path}{os.path.sep}{filename}", 'w') as fp:
            json.dump(self.monitors, fp)


    def loadCache(self, filename):
        logger.info(f"Loading KM repository from cache '{filename}' ...")
        with open(filename) as fp:
            self.monitors = json.load(fp)

#-----------------------
# Utils
# ----------------------
defaultRepositoryDir="bmc_products"
defaultTenantId="*"
defaultTenantName="*"
defaultPrecedence="399"
defaultFilename="thresholds.csv"
defaultOut="out"
defaultDirectory="."
defaultOwner="admin"
defaultGroup="Administrators"
defaultCache="cache"


def parseArguments():
    parser = parser = argparse.ArgumentParser(description='Generate TrueSight monitoring policies from instance thresholds.')
    cmdParsers = parser.add_subparsers( dest="cmd", help='sub-command help' )
    migrateCmd = cmdParsers.add_parser('migrate', help='Migrate  ...')
    migrateCmd.add_argument('-r','--repository', action="store", dest="repositoryDir",
        help=f"path to the bmc repository. The default path is '{defaultRepositoryDir}'. The repository is needed to gather information about solutions to be able to create policies.")

    migrateCmd.add_argument('--version', action="store", dest="version",
        help=f"path to the bmc repository. The default path is '{defaultRepositoryDir}'. The repository is needed to gather information about solutions to be able to create policies.")

    migrateCmd.add_argument("--tenantId", action="store", dest="tenantId",
        help=f"Tenant id to be used in policy generation. The default tenant id is '{defaultTenantId}'.")

    migrateCmd.add_argument("--tenantName", action="store", dest="tenantName",
        help=f"Tenant name to be used in policy generation The default tenant name is '{defaultTenantName}'.")

    migrateCmd.add_argument("-p", "--precedence", action="store", dest="precedence",
        help=f"precedence to be used in policy generation. The default precedence is '{defaultPrecedence}'.")

    migrateCmd.add_argument("-f", "--file", action="store", dest="filename",
        help=f"name of the file which which contains the thresholds exported from tsps. The default file name is '{defaultFilename}'")

    migrateCmd.add_argument("-o", "--out", action="store", dest="out",
        help=f"path to the directory where the generated policies should be stored. The default is '{defaultOut}'.'")
    
    migrateCmd.add_argument("-d", "--directory", action="store", dest="directory",
        help=f"path to the directory where the exported threshold files reside. The default directory is '{defaultDirectory}'")

    migrateCmd.add_argument("--owner", action="store", dest="owner",
        help=f"name of the owner of the policy. The default owner is '{defaultOwner}'.")

    migrateCmd.add_argument("--shared", action="store_true", dest="shared", 
        help=f"share the generated policy. The default is that the policy is not shared")

    migrateCmd.add_argument("--enabled", action="store_true", dest="enabled", 
        help=f"enable the generated policy. The default is that the policy is not enabled")

    migrateCmd.add_argument("--group", action="store", dest="group",
        help=f"name of the group to be used in the generated policy. The default group is '{defaultGroup}'.")

    kmrepoCmd = cmdParsers.add_parser('kmrepo', 
        help="Manage the km repo. This command is used to create caches of the KM Repository which can be distributed with the product " +
            "KM Repository caches are slim version of the KM repository which just contain the information the utility needs.")

    kmrepoCmd.add_argument('-r','--repository', action="store", dest="repositoryDir",
        help=f"path to the bmc repository. The default path is '{defaultRepositoryDir}'. The repository is needed to gather information about solutions to be able to create policies.")

    kmrepoCmd.add_argument('--version', action="store", dest="version", required=True,
        help=f"path to the bmc repository. The default path is '{defaultRepositoryDir}'. The repository is needed to gather information about solutions to be able to create policies.")

    kmrepoCmd.add_argument('--cache', action="store", dest="cache", required=False,
        help=f"path to the bmc repository. The default path is '{defaultRepositoryDir}'. The repository is needed to gather information about solutions to be able to create policies.")

    return parser.parse_args()


def getDefaults(args):
    defaults = {}
    defaults["repositoryDir"] = args.repositoryDir if hasattr(args, "repositoryDir") and args.repositoryDir != None else defaultRepositoryDir
    defaults["tenantId"] = args.tenantId if hasattr(args, "tenantId") and args.tenantId != None else defaultTenantId
    defaults["tenantName"] = args.tenantName if hasattr(args, "tenantName") and args.tenantName != None else defaultTenantName
    defaults["agentPrecedence"] = args.precedence if hasattr(args, "precedence") and args.precedence != None else defaultPrecedence
    defaults["filename"] = args.filename if hasattr(args, "filename") and args.filename != None else defaultFilename
    defaults["out"] = args.out if hasattr(args, "out") and args.out != None else defaultOut
    defaults["owner"] = args.owner if hasattr(args, "owner") and args.owner != None else defaultOwner
    defaults["cache"] = args.cache if hasattr(args, "cache") and args.cache != None else defaultCache
    defaults["shared"] = args.shared if hasattr(args, "shared") and args.shared != None else False
    defaults["enabled"] = args.enabled if hasattr(args, "enabled") and args.enabled != None else False
    defaults["associatedUserGroup"] = args.group if hasattr(args, "group") and args.group != None else defaultGroup
    defaults["version"] = args.version if hasattr(args, "version") and args.version else "unknown"
 
    return defaults

def dump(policies, path):
    logger.info(f"Writing polycies to directory '{path}' ...")
    os.makedirs(path, exist_ok = True)
    for policy in policies.values():
        with open(f"{path}{os.path.sep}{policy['name']}.mo", 'w') as fp:
            json.dump([policy], fp)

def getKMRepository(cachedir, repositorydir, version):
    if repositorydir != None:
        kmRepository = KMRepository(f"{repositorydir}{os.path.set}bmc_products{os.path.sep}kmfiles")
        kmRepository.load()

    elif version != None:
        kmRepository = KMRepository()
        kmRepository.loadCache(f"{cachedir}{os.path.sep}{version}")

    else:
        # get the highest version
        l = glob.glob(f"{cachedir}{os.path.sep}*")
        l.sort(reverse=True)
        kmRepository = KMRepository()
        kmRepository.loadCache(l[0])

    return kmRepository


def migrateCmd(kmRepository, outputPath, thresholdFilename):
    # load the Threshold File
    thresholdSet = FileThresholdSet(thresholdFilename)
    thresholdSet.load()

    # Migrate Thresholds
    instanceThresholdMigrator = InstanceThresholdMigrator(thresholdSet)
    configurations = instanceThresholdMigrator.migrate()

    # Generate Policies
    policyFactory = PolicyFactory(kmRepository, defaults)
    policyFactory.configurations.extend(configurations)
    policies = policyFactory.generatePolicies()

    # Write Policies to file
    dump(policies, outputPath)

def kmrepoCmd():
    kmRepository = KMRepository(f"{defaults['repositoryDir']}{os.path.sep}bmc_products{os.path.sep}kmfiles")
    kmRepository.load()
    kmRepository.saveCache(defaults['cache'], defaults['version'])

#-----------------------
# Main
#-----------------------

version = "1.0.0"

logger = LoggerFactory.getLogger(__name__)
logger.info(f"{__file__} CMA Utility Version {version} (c) 2020 BMC Software Inc.")

args = parseArguments()
defaults = getDefaults(args)

if args.cmd == "migrate":
    kmRepository = getKMRepository(defaults["cache"], args.repositoryDir, args.version) 
    migrateCmd(kmRepository, outputPath=defaults["out"], thresholdFilename=defaults["filename"])

elif args.cmd == "kmrepo":
    kmrepoCmd(args.version, args.repositoryDir)

else: logger.error(f"Unknown command '{args.cmd}'used in command line.")

logger.info("done.")